import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';


const Test: NextPage = () => {
  const myStyle = {
    color: 'red',
    fontSize: '16px',
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <div className={styles.main}>
        <ConnectButton />
      </div>
    </div>
  );
};

export default Test; 
