import { ConnectButton } from "@rainbow-me/rainbowkit";
import Image from "next/image";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import img1 from "../public/images/ru.svg";
import img2 from "../public/images/left.svg";

const Home: NextPage = () => {
  const itemList = [
    {
      id: 1,
      label:
        "No KYC Required: Enjoy transfer coins transactions between accounts without the hassle.",
      iconSrc: "../public/images/ru.svg",
    },
    {
      id: 2,
      label:
        "No KYC Required: Enjoy transfer coins transactions between accounts without the hassle.",
      iconSrc: "/icons/icon2.png",
    },
    {
      id: 3,
      label:
        "No KYC Required: Enjoy transfer coins transactions between accounts without the hassle.",
      iconSrc: "/icons/icon3.png",
    },
    {
      id: 4,
      label:
        "No KYC Required: Enjoy transfer coins transactions between accounts without the hassle.",
      iconSrc: "/icons/icon4.png",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Athene</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        {/* header */}
        <div className={styles.header}>
          <div className={styles.logo}>Athene</div>
          <div className={styles.actionBtn}>
            <div className={styles.actionBtnConnet}>
              <ConnectButton label="Connect Wallet" />
            </div>
            <div className={styles.actionBtnSelect}>
              <select className={styles.actionBtnSelectLang} name="" id="">
                <option className={styles.actionBtnOption} value="">
                  <div>{/* <Image src={img1} alt="picture" /> */}</div>
                  <div>Việt Nam</div>
                </option>
                <option className={styles.actionBtnOption} value="">
                  English
                </option>
                <option className={styles.actionBtnOption} value="">
                  Đức
                </option>
                <option className={styles.actionBtnOption} value="">
                  English
                </option>
                <option className={styles.actionBtnOption} value="">
                  English
                </option>
              </select>
              <div>
                <Image src={img2} alt="" />
              </div>
            </div>
          </div>
        </div>
        {/* content */}
        <div className={styles.homeContent}>
          <div className={styles.homeContentTitle}>
            Welcome to Athene Network
          </div>
          <div className={styles.homeContentSub}>
            Please connect your wallet to purchase the Premium Package. With
            only $3, you will get incredible benefits
          </div>
          <div className={styles.homeContentChooie}>
            <ul>
              {itemList.map((item, index) => (
                <li key={item.id}>
                  <div>
                    <img src={item.iconSrc} alt={item.label} />
                  </div>
                  <div>{item.label}</div>
                </li>
              ))}
            </ul>
          </div>
          <div className={styles.homeContentGemTitle}>
            For every user you introduce who purchases the Premium Package,
            you'll earn fantastic commissions
          </div>
          <div>
            <ul>
              {itemList.map((item, index) => (
                <li key={item.id}>
                  <div>
                    <img src={item.iconSrc} alt={item.label} />
                  </div>
                  <div>{item.label}</div>
                </li>
              ))}
            </ul>
          </div>
          <div className={styles.homeContentPurchase}>
            <div>

            </div>
            <div>
              <img src="../assets/images/Chevron_Left.svg" alt="" />
            </div>
            <div>12312312</div>

          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
