import { ConnectButton } from "@rainbow-me/rainbowkit";
import Image from "next/image";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import img1 from "../public/images/ru.svg";
import img2 from "../public/images/left.svg";
import img3 from "../public/images/Interface.svg";
import img4 from "../public/images/Gem.png";
import React, { useState } from "react";
import Select from 'react-select';

const Home: NextPage = () => {
  const [showSubtitle, setShowSubtitle] = useState(false);
  const itemList = [
    {
      id: 1,
      label:
        "No KYC Required: Enjoy transfer coins transactions between accounts without the hassle.",
      iconSrc: img3,
    },
    {
      id: 2,
      label:
        "Deposit ATH to Athene Gaming and Athene Prediction: Immerse yourself in the gaming world like never before.",
      iconSrc: img3,
    },
    {
      id: 3,
      label: "Increase the Booster Coefficient by 30% on the Athene App.",
      iconSrc: img3,
    },
    {
      id: 4,
      label: " And many more special benefits to elevate your experience.",
      iconSrc: img3,
    },
  ];
  const itemListGem = [
    {
      id: 1,
      label: "F1: $1/ref",
      iconSrc: img4,
    },
    {
      id: 2,
      label: "F2: $0.5/ref",
      iconSrc: img4,
    },
  ];
  const itemListPurchase = [
    {
      id: 1,
      label: "1. Connect your wallet by clicking the button 'Connect Wallet'",
    },
    {
      id: 2,
      label: "2. Enter your Athene account (your email)",
    },
    {
      id: 3,
      label: "3. Click the 'Buy Premium' button and confirm the transaction",
    },
    {
      id: 4,
      label:
        "4. The system will automatically process transactions and update your account's Premium Package.",
    },
  ];
  const handleClick = () => {
    setShowSubtitle(!showSubtitle);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Athene</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        {/* header */}
        <div className={styles.header}>
          <div className={styles.logo}>Athene</div>
          <div className={styles.actionBtn}>
            <div className={styles.actionBtnConnet}>
              <ConnectButton label="Connect Wallet" />
            </div>
            <div className={styles.actionBtnSelect}>
              <select className={styles.actionBtnSelectLang} name="" id="">
                <option className={styles.actionBtnOption} value="">
                  <Image src={img1} alt="picture" />
                  <span>Việt Nam</span>
                </option>
                <option className={styles.actionBtnOption} value="">
                  English
                </option>
                <option className={styles.actionBtnOption} value="">
                  Đức
                </option>
                <option className={styles.actionBtnOption} value="">
                  English
                </option>
                <option className={styles.actionBtnOption} value="">
                  English
                </option>
              </select>
              <div>
                <Image src={img2} alt="" />
              </div>
            </div>
          </div>
        </div>
        {/* content */}
        <div className={styles.homeContent}>
          <div className={styles.homeContentTitle}>
            Welcome to Athene Network
          </div>
          <div className={styles.homeContentSub}>
            Please connect your wallet to purchase the Premium Package. With
            only $3, you will get incredible benefits
          </div>
          <div className={styles.homeContentChooie}>
            <ul>
              {itemList.map((item, index) => (
                <li key={item.id} className={styles.homeContentChooieItem}>
                  <Image
                    src={item.iconSrc}
                    alt="picture"
                    layout="fixed"
                    width={16}
                    height={16}
                    className={styles.homeContentChooieImage}
                  />
                  <div className={styles.homeContentChooieItemText}>
                    {item.label}
                  </div>
                </li>
              ))}
            </ul>
          </div>
          <div className={styles.homeContentGemTitle}>
            For every user you introduce who purchases the Premium Package,
            you'll earn fantastic commissions
          </div>
          <div className={styles.homeContentGemItem}>
            <ul>
              {itemListGem.map((item, index) => (
                <li key={item.id} className={styles.homeContentGemItemMain}>
                  <Image
                    src={item.iconSrc}
                    alt="picture"
                    layout="fixed"
                    width={16}
                    height={16}
                    className={styles.homeContentChooieImage}
                  />
                  <div className={styles.homeContentGemItemText}>
                    {item.label}
                  </div>
                </li>
              ))}
            </ul>
          </div>
          <div className={styles.homeContentPurchase}>
            <div className={styles.homeContentPurchaseContainer}>
              <div>
                <div
                  className={styles.homeContentPurchaseMain}
                  onClick={handleClick}
                >
                  <div className={styles.homeContentPurchaseTitle}>
                    How to purchase?
                  </div>
                  <Image
                    src={img2}
                    alt="picture"
                    layout="fixed"
                    width={16}
                    height={16}
                    className={styles.homeContentChooieImage}
                  />
                </div>
              </div>
              {showSubtitle && (
                <div className={styles.homeContentPurchaseSubTitle}>
                  <div className={styles.homeContentPurchaseSubTitleItem}>
                    {itemListPurchase.map((item, index) => (
                      <li
                        key={item.id}
                        className={styles.homeContentPurchaseSubTitleMain}
                      >
                        <div className={styles.homeContentPurchaseSubTitleText}>
                          {item.label}
                        </div>
                      </li>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
          <div className={styles.homeContentSubmit}>
            <div className={styles.homeContentSubmitContainer}>
              <input
                className={styles.homeContentSubmitInput}
                placeholder="Thiquynhnguyenptit@gmail.com"
                type="text"
              />
              <div>
                <button className={styles.homeContentSubmitBtn}>
                  BUY PREMIUM
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.homeContentTextEnd}>
          THANK YOU FOR CHOOSING ATHENE NETWORK!
        </div>
        <div className={styles.homeFooter}>
          2024 Athene Group LTD. | All rights reserved.
        </div>
      </main>
    </div>
  );
};

export default Home;
